/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package tela;

import dao.AutomovelDao;
import dao.ModeloDao;
import java.util.ArrayList;
import java.util.List;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import modelo.Automovel;
import modelo.Modelo;

/**
 *
 * @author gledson.cruz
 */
public class FrmAutomovel extends javax.swing.JInternalFrame {

    //Declaracao das variaveis globais
    Automovel auto = new Automovel();
    AutomovelDao autoDao = new AutomovelDao();
    ModeloDao modeloDao = new ModeloDao();
    List<Automovel> autos = new ArrayList<>();
    List<Modelo> modelos = new ArrayList<>();

    /**
     * Creates new form FrmAutomovel
     */
    public FrmAutomovel() {
        initComponents();
        this.autos = autoDao.carregarTodos();
        this.modelos = modeloDao.carregarTodos();
        carregarTabela(autos);
        carregarCombo();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane2 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        lblAnoFabricacao = new javax.swing.JLabel();
        txtAnoFabricacao = new javax.swing.JTextField();
        lblAnoModelo = new javax.swing.JLabel();
        txtAnoModelo = new javax.swing.JTextField();
        lblPreco = new javax.swing.JLabel();
        txtPreco = new javax.swing.JTextField();
        lblKilometragem = new javax.swing.JLabel();
        txtKilometragem = new javax.swing.JTextField();
        lblModelo = new javax.swing.JLabel();
        cbModelo = new javax.swing.JComboBox();
        lblObservacoes = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtObservacoes = new javax.swing.JTextArea();
        pnlBotoes = new javax.swing.JPanel();
        btnInserir = new javax.swing.JButton();
        btnAlterar = new javax.swing.JButton();
        btnExcluir = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();
        pnlConsulta = new javax.swing.JPanel();
        lblConsultar = new javax.swing.JLabel();
        txtConsultar = new javax.swing.JTextField();
        jScrollPane3 = new javax.swing.JScrollPane();
        tblAutomovel = new javax.swing.JTable();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(jTable1);

        setTitle("Automovel");

        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        lblAnoFabricacao.setText("Ano da Fabricação:");

        lblAnoModelo.setText("Ano do Modelo:");

        lblPreco.setText("Preço:");

        lblKilometragem.setText("Kilometragem:");

        lblModelo.setText("Modelo:");

        lblObservacoes.setText("Observações:");

        txtObservacoes.setColumns(20);
        txtObservacoes.setRows(5);
        jScrollPane1.setViewportView(txtObservacoes);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblAnoFabricacao)
                    .addComponent(lblKilometragem)
                    .addComponent(lblObservacoes))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(txtKilometragem, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtAnoFabricacao, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(lblModelo)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(cbModelo, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(lblAnoModelo)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtAnoModelo, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(lblPreco)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtPreco, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 524, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(51, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblAnoFabricacao)
                    .addComponent(txtAnoFabricacao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblAnoModelo)
                    .addComponent(txtAnoModelo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblPreco)
                    .addComponent(txtPreco, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblKilometragem)
                    .addComponent(txtKilometragem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblModelo)
                    .addComponent(cbModelo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblObservacoes)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pnlBotoes.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        btnInserir.setText("Inserir");
        btnInserir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInserirActionPerformed(evt);
            }
        });

        btnAlterar.setText("Alterar");
        btnAlterar.setEnabled(false);
        btnAlterar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAlterarActionPerformed(evt);
            }
        });

        btnExcluir.setText("Excluir");
        btnExcluir.setEnabled(false);
        btnExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExcluirActionPerformed(evt);
            }
        });

        btnCancelar.setText("Cancelar");
        btnCancelar.setEnabled(false);
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlBotoesLayout = new javax.swing.GroupLayout(pnlBotoes);
        pnlBotoes.setLayout(pnlBotoesLayout);
        pnlBotoesLayout.setHorizontalGroup(
            pnlBotoesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlBotoesLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnInserir)
                .addGap(18, 18, 18)
                .addComponent(btnAlterar)
                .addGap(18, 18, 18)
                .addComponent(btnExcluir)
                .addGap(18, 18, 18)
                .addComponent(btnCancelar)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnlBotoesLayout.setVerticalGroup(
            pnlBotoesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlBotoesLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlBotoesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnInserir)
                    .addComponent(btnAlterar)
                    .addComponent(btnExcluir)
                    .addComponent(btnCancelar))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pnlConsulta.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        lblConsultar.setText("Consultar:");

        tblAutomovel.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        tblAutomovel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblAutomovelMouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(tblAutomovel);

        javax.swing.GroupLayout pnlConsultaLayout = new javax.swing.GroupLayout(pnlConsulta);
        pnlConsulta.setLayout(pnlConsultaLayout);
        pnlConsultaLayout.setHorizontalGroup(
            pnlConsultaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlConsultaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlConsultaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane3)
                    .addGroup(pnlConsultaLayout.createSequentialGroup()
                        .addComponent(lblConsultar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtConsultar, javax.swing.GroupLayout.PREFERRED_SIZE, 222, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        pnlConsultaLayout.setVerticalGroup(
            pnlConsultaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlConsultaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlConsultaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblConsultar)
                    .addComponent(txtConsultar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pnlBotoes, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pnlConsulta, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pnlBotoes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pnlConsulta, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnInserirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInserirActionPerformed
        // TODO add your handling code here:
        // Seto o nome da marca no Objeto marca
        this.auto.setAnoFabricacao(Integer.parseInt(txtAnoFabricacao.getText()));
        this.auto.setAnoModelo(Integer.parseInt(txtAnoModelo.getText()));
        this.auto.setKilometragem(Integer.parseInt(txtKilometragem.getText()));
        this.auto.setModelo((Modelo) cbModelo.getSelectedItem());
        this.auto.setObservacoes(txtObservacoes.getText());
        this.auto.setPreco(Double.parseDouble(txtPreco.getText()));
        // Chamo o metodo salvar do marcaDao passando o objeto marca como parametro
        this.autoDao.salvar(this.auto);
        // Recarrego a lista de marcas
        this.autos = autoDao.carregarTodos();
        // Recarrego a tabela de marcas da tela
        carregarTabela(autos);
        // Limpo os campos
        limparCampos();
        // Jogo o foco no campo marca da tela
        txtAnoFabricacao.requestFocus();
        // Apresento a mensagem na tela
        JOptionPane.showMessageDialog(this, "Salvo com sucesso!",
                "Informação", JOptionPane.INFORMATION_MESSAGE);

    }//GEN-LAST:event_btnInserirActionPerformed

    private void btnAlterarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAlterarActionPerformed
        // TODO add your handling code here:

        this.auto.setAnoFabricacao(Integer.parseInt(txtAnoFabricacao.getText()));
        this.auto.setAnoModelo(Integer.parseInt(txtAnoModelo.getText()));
        this.auto.setKilometragem(Integer.parseInt(txtKilometragem.getText()));
        this.auto.setModelo((Modelo) cbModelo.getSelectedItem());
        this.auto.setObservacoes(txtObservacoes.getText());
        this.auto.setPreco(Double.parseDouble(txtPreco.getText()));
        this.autoDao.alterar(this.auto);
        // Recarrego a lista de marcas
        this.autos = autoDao.carregarTodos();
        // Recarrego a tabela de marcas da tela
        carregarTabela(this.autos);
        // Limpo os campos
        limparCampos();
        // Jogo o foco no campo marca da tela
        txtAnoFabricacao.requestFocus();
        JOptionPane.showMessageDialog(this, "Alterado com sucesso!",
                "Informação", JOptionPane.INFORMATION_MESSAGE);

        ctrlBtn();
    }//GEN-LAST:event_btnAlterarActionPerformed

    private void btnExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExcluirActionPerformed
        // TODO add your handling code here:

        int selectedOption = JOptionPane.showConfirmDialog(null, "Tem certeza?", "Sistema informa:", JOptionPane.YES_NO_OPTION);
        if (selectedOption == JOptionPane.YES_OPTION) {

            this.autoDao.excluir(this.auto);
            // Recarrego a lista de marcas
            this.autos = autoDao.carregarTodos();
            // Recarrego a tabela de marcas da tela
            carregarTabela(this.autos);
            // Limpo os campos
            limparCampos();
            // Jogo o foco no campo marca da tela
            txtAnoFabricacao.requestFocus();
            ctrlBtn();
            JOptionPane.showMessageDialog(this, "Excluido com sucesso",
                    "Informação", JOptionPane.INFORMATION_MESSAGE);
        }


    }//GEN-LAST:event_btnExcluirActionPerformed

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        // TODO add your handling code here:
        limparCampos();
        txtAnoFabricacao.requestFocus();
        this.auto = new Automovel();
        ctrlBtn();
    }//GEN-LAST:event_btnCancelarActionPerformed

    private void tblAutomovelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblAutomovelMouseClicked
        // TODO add your handling code here:
        if (evt.getClickCount() > 1) {
            
            this.auto = this.autos.get(tblAutomovel.convertRowIndexToModel(tblAutomovel.getSelectedRow()));
            txtAnoFabricacao.setText(this.auto.getAnoFabricacao().toString());
            txtAnoModelo.setText(this.auto.getAnoModelo().toString());
            txtKilometragem.setText(this.auto.getKilometragem().toString());
            txtObservacoes.setText(this.auto.getObservacoes());
            txtPreco.setText(this.auto.getPreco().toString());
            cbModelo.setSelectedItem(this.auto.getModelo());
            ctrlBtn();
        }
    }//GEN-LAST:event_tblAutomovelMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAlterar;
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnExcluir;
    private javax.swing.JButton btnInserir;
    private javax.swing.JComboBox cbModelo;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTable jTable1;
    private javax.swing.JLabel lblAnoFabricacao;
    private javax.swing.JLabel lblAnoModelo;
    private javax.swing.JLabel lblConsultar;
    private javax.swing.JLabel lblKilometragem;
    private javax.swing.JLabel lblModelo;
    private javax.swing.JLabel lblObservacoes;
    private javax.swing.JLabel lblPreco;
    private javax.swing.JPanel pnlBotoes;
    private javax.swing.JPanel pnlConsulta;
    private javax.swing.JTable tblAutomovel;
    private javax.swing.JTextField txtAnoFabricacao;
    private javax.swing.JTextField txtAnoModelo;
    private javax.swing.JTextField txtConsultar;
    private javax.swing.JTextField txtKilometragem;
    private javax.swing.JTextArea txtObservacoes;
    private javax.swing.JTextField txtPreco;
    // End of variables declaration//GEN-END:variables

    private void carregarTabela(List<Automovel> autos) {
        AutomovelTableModel tabela = new AutomovelTableModel(autos);
        tblAutomovel.setModel(tabela);
        tblAutomovel.setRowHeight(30);
        tblAutomovel.setAutoResizeMode(JTable.AUTO_RESIZE_LAST_COLUMN);
        tblAutomovel.getColumnModel().getColumn(0).setPreferredWidth(100);
        tblAutomovel.getColumnModel().getColumn(1).setPreferredWidth(200);
        tblAutomovel.getColumnModel().getColumn(2).setPreferredWidth(200);
        tblAutomovel.getColumnModel().getColumn(3).setPreferredWidth(200);
        tblAutomovel.getColumnModel().getColumn(4).setPreferredWidth(200);
        tblAutomovel.getColumnModel().getColumn(5).setPreferredWidth(200);
    }

    private void limparCampos() {
        txtAnoFabricacao.setText("");
        txtAnoModelo.setText("");
        txtConsultar.setText("");
        txtKilometragem.setText("");
        txtObservacoes.setText("");
        txtPreco.setText("");
    }

    private void ctrlBtn() {
        btnInserir.setEnabled(!btnInserir.isEnabled());
        btnAlterar.setEnabled(!btnAlterar.isEnabled());
        btnExcluir.setEnabled(!btnExcluir.isEnabled());
        btnCancelar.setEnabled(!btnCancelar.isEnabled());
    }
    
    private void carregarCombo() {
        
        DefaultComboBoxModel<Modelo> modeloComboModel = (DefaultComboBoxModel) cbModelo.getModel();

        for (Modelo obj : this.modelos) {            
            modeloComboModel.addElement(obj);
        }

        
    }
}
