/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package tela;

import dao.MarcaDao;
import dao.ModeloDao;
import java.util.ArrayList;
import java.util.List;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import modelo.Marca;
import modelo.Modelo;

/**
 *
 * @author gledson.cruz
 */
public class FrmModelo extends javax.swing.JInternalFrame {
    
    //Declaracao das variaveis globais
    Modelo modelo = new Modelo();
    ModeloDao modeloDao = new ModeloDao();
    MarcaDao marcaDao = new MarcaDao();
    List<Modelo> modelos = new ArrayList<>();
    List<Marca> marcas = new ArrayList<>();

    /**
     * Creates new form FrmModelo
     */
    public FrmModelo() {
        initComponents();
        this.marcas = marcaDao.carregarTodos();
        this.modelos = modeloDao.carregarTodos();
        carregarCombo();
        carregarTabela(this.modelos);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlModelo = new javax.swing.JPanel();
        lblDescricao = new javax.swing.JLabel();
        txtDescricao = new javax.swing.JTextField();
        lblPotencia = new javax.swing.JLabel();
        txtPotencia = new javax.swing.JTextField();
        cbMarca = new javax.swing.JComboBox();
        lblMarca = new javax.swing.JLabel();
        pnlBotoes = new javax.swing.JPanel();
        btnInserir = new javax.swing.JButton();
        btnAlterar = new javax.swing.JButton();
        btnExcluir = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        lblConsultar = new javax.swing.JLabel();
        txtConsultar = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblModelo = new javax.swing.JTable();

        setTitle("Modelo");

        pnlModelo.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        lblDescricao.setText("Descrição:");

        lblPotencia.setText("Potência:");

        lblMarca.setText("Marca:");

        javax.swing.GroupLayout pnlModeloLayout = new javax.swing.GroupLayout(pnlModelo);
        pnlModelo.setLayout(pnlModeloLayout);
        pnlModeloLayout.setHorizontalGroup(
            pnlModeloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlModeloLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlModeloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblDescricao)
                    .addComponent(lblPotencia)
                    .addComponent(lblMarca))
                .addGap(18, 18, 18)
                .addGroup(pnlModeloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtPotencia, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbMarca, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtDescricao, javax.swing.GroupLayout.PREFERRED_SIZE, 272, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnlModeloLayout.setVerticalGroup(
            pnlModeloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlModeloLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlModeloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblDescricao)
                    .addComponent(txtDescricao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlModeloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblPotencia)
                    .addComponent(txtPotencia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlModeloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblMarca)
                    .addComponent(cbMarca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pnlBotoes.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        btnInserir.setText("Inserir");
        btnInserir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInserirActionPerformed(evt);
            }
        });

        btnAlterar.setText("Alterar");
        btnAlterar.setEnabled(false);
        btnAlterar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAlterarActionPerformed(evt);
            }
        });

        btnExcluir.setText("Excluir");
        btnExcluir.setEnabled(false);
        btnExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExcluirActionPerformed(evt);
            }
        });

        btnCancelar.setText("Cancelar");
        btnCancelar.setEnabled(false);
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlBotoesLayout = new javax.swing.GroupLayout(pnlBotoes);
        pnlBotoes.setLayout(pnlBotoesLayout);
        pnlBotoesLayout.setHorizontalGroup(
            pnlBotoesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlBotoesLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnInserir)
                .addGap(18, 18, 18)
                .addComponent(btnAlterar)
                .addGap(18, 18, 18)
                .addComponent(btnExcluir)
                .addGap(18, 18, 18)
                .addComponent(btnCancelar)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnlBotoesLayout.setVerticalGroup(
            pnlBotoesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlBotoesLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlBotoesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnInserir)
                    .addComponent(btnAlterar)
                    .addComponent(btnExcluir)
                    .addComponent(btnCancelar))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        lblConsultar.setText("Consultar:");

        txtConsultar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtConsultarKeyReleased(evt);
            }
        });

        tblModelo.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        tblModelo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblModeloMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblModelo);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 761, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(lblConsultar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtConsultar, javax.swing.GroupLayout.PREFERRED_SIZE, 271, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblConsultar)
                    .addComponent(txtConsultar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 196, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pnlModelo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pnlBotoes, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pnlModelo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pnlBotoes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnInserirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInserirActionPerformed
        // TODO add your handling code here:
        // Seto o nome da marca no Objeto marca
        this.modelo.setDescricao(txtDescricao.getText());
        this.modelo.setPotencia(Integer.parseInt(txtPotencia.getText()));
        this.modelo.setMarca((Marca) cbMarca.getSelectedItem());
        // Chamo o metodo salvar do marcaDao passando o objeto marca como parametro
        this.modeloDao.salvar(this.modelo);
        // Recarrego a lista de marcas
        this.modelos = modeloDao.carregarTodos();
        // Recarrego a tabela de marcas da tela
        carregarTabela(modelos);
        // Limpo os campos
        limparCampos();
        // Jogo o foco no campo marca da tela
        txtDescricao.requestFocus();
        // Apresento a mensagem na tela
        JOptionPane.showMessageDialog(this, "Salvo com sucesso!",
            "Informação", JOptionPane.INFORMATION_MESSAGE);

    }//GEN-LAST:event_btnInserirActionPerformed

    private void btnAlterarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAlterarActionPerformed
        // TODO add your handling code here:

        this.modelo.setDescricao(txtDescricao.getText());
        this.modelo.setMarca((Marca) cbMarca.getSelectedItem());
        this.modeloDao.alterar(this.modelo);
        // Recarrego a lista de modelos
        this.modelos = modeloDao.carregarTodos();
        // Recarrego a tabela de modelos da tela
        carregarTabela(modelos);
        // Limpo os campos
        limparCampos();
        // Jogo o foco no campo descricao da tela
        txtDescricao.requestFocus();
        JOptionPane.showMessageDialog(this, "Alterado com sucesso!",
            "Informação", JOptionPane.INFORMATION_MESSAGE);

        ctrlBtn();
    }//GEN-LAST:event_btnAlterarActionPerformed

    private void btnExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExcluirActionPerformed
        // TODO add your handling code here:
        if (this.modelo.getAutomoveis().size() > 0) {
            JOptionPane.showMessageDialog(this, "Essa marca possui automoveis(s) relacionado(s)",
                "Informação", JOptionPane.ERROR_MESSAGE);
        } else {
            int selectedOption = JOptionPane.showConfirmDialog(null, "Tem certeza?", "Sistema informa:", JOptionPane.YES_NO_OPTION);
            if (selectedOption == JOptionPane.YES_OPTION) {

                this.modeloDao.excluir(this.modelo);
                // Recarrego a lista de modelos
                this.modelos = modeloDao.carregarTodos();
                // Recarrego a tabela de marcas da tela
                carregarTabela(this.modelos);
                // Limpo os campos
                limparCampos();
                // Jogo o foco no campo marca da tela
                txtDescricao.requestFocus();
                ctrlBtn();
                JOptionPane.showMessageDialog(this, "Excluido com sucesso",
                    "Informação", JOptionPane.INFORMATION_MESSAGE);
            }

        }
    }//GEN-LAST:event_btnExcluirActionPerformed

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        // TODO add your handling code here:
        limparCampos();
        txtDescricao.requestFocus();
        this.modelo = new Modelo();
        ctrlBtn();
    }//GEN-LAST:event_btnCancelarActionPerformed

    private void tblModeloMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblModeloMouseClicked
        // TODO add your handling code here:
        if (evt.getClickCount() > 1) {
            // Pego a linha selecionada da tabela e jogo pro objeto
            this.modelo = this.modelos.get(tblModelo.convertRowIndexToModel(tblModelo.getSelectedRow()));
            // Jogo o nome da marca na caixa de texto
            txtDescricao.setText(this.modelo.getDescricao());
            txtPotencia.setText(this.modelo.getPotencia().toString());
            cbMarca.setSelectedItem(this.modelo.getMarca());
            ctrlBtn();
        }
    }//GEN-LAST:event_tblModeloMouseClicked

    private void txtConsultarKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtConsultarKeyReleased
        // TODO add your handling code here:
        
        this.modelos = modeloDao.carregarPorDescricao(txtConsultar.getText());
        carregarTabela(this.modelos);
    }//GEN-LAST:event_txtConsultarKeyReleased


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAlterar;
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnExcluir;
    private javax.swing.JButton btnInserir;
    private javax.swing.JComboBox cbMarca;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblConsultar;
    private javax.swing.JLabel lblDescricao;
    private javax.swing.JLabel lblMarca;
    private javax.swing.JLabel lblPotencia;
    private javax.swing.JPanel pnlBotoes;
    private javax.swing.JPanel pnlModelo;
    private javax.swing.JTable tblModelo;
    private javax.swing.JTextField txtConsultar;
    private javax.swing.JTextField txtDescricao;
    private javax.swing.JTextField txtPotencia;
    // End of variables declaration//GEN-END:variables

    private void limparCampos() {
        txtDescricao.setText("");
        txtPotencia.setText("");
        txtConsultar.setText("");
        cbMarca.setSelectedIndex(0);
    }

    private void ctrlBtn() {
        btnInserir.setEnabled(!btnInserir.isEnabled());
        btnAlterar.setEnabled(!btnAlterar.isEnabled());
        btnExcluir.setEnabled(!btnExcluir.isEnabled());
        btnCancelar.setEnabled(!btnCancelar.isEnabled());
    }

    private void carregarTabela(List<Modelo> modelos) {
        ModeloTableModel tabela = new ModeloTableModel(modelos);
        tblModelo.setModel(tabela);
        tblModelo.setRowHeight(30);
        tblModelo.setAutoResizeMode(JTable.AUTO_RESIZE_LAST_COLUMN);
        tblModelo.getColumnModel().getColumn(0).setPreferredWidth(100);
        tblModelo.getColumnModel().getColumn(1).setPreferredWidth(400);
        tblModelo.getColumnModel().getColumn(2).setPreferredWidth(400);
        tblModelo.getColumnModel().getColumn(3).setPreferredWidth(400);
    }
    
    private void carregarCombo() {
        
        DefaultComboBoxModel<Marca> marcaComboModel = (DefaultComboBoxModel) cbMarca.getModel();

        for (Marca obj : this.marcas) {            
            marcaComboModel.addElement(obj);
        }

        
    }
}
